<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KotaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $kotas = [
            ['kode_kota' => 1101, 'id_provinsi' => 1, 'nama_kota' => "KABUPATEN SIMEULUE"],
			['kode_kota' => 1102, 'id_provinsi' => 1, 'nama_kota' => "KABUPATEN ACEH SINGKIL"],
			['kode_kota' => 1103, 'id_provinsi' => 1, 'nama_kota' => "KABUPATEN ACEH SELATAN"],
			['kode_kota' => 1104, 'id_provinsi' => 1, 'nama_kota' => "KABUPATEN ACEH TENGGARA"],
			['kode_kota' => 1105, 'id_provinsi' => 1, 'nama_kota' => "KABUPATEN ACEH TIMUR"],
			['kode_kota' => 1106, 'id_provinsi' => 1, 'nama_kota' => "KABUPATEN ACEH TENGAH"],
			['kode_kota' => 1107, 'id_provinsi' => 1, 'nama_kota' => "KABUPATEN ACEH BARAT"],
			['kode_kota' => 1108, 'id_provinsi' => 1, 'nama_kota' => "KABUPATEN ACEH BESAR"],
			['kode_kota' => 1109, 'id_provinsi' => 1, 'nama_kota' => "KABUPATEN PIDIE"],
			['kode_kota' => 1110, 'id_provinsi' => 1, 'nama_kota' => "KABUPATEN BIREUEN"],
			['kode_kota' => 1111, 'id_provinsi' => 1, 'nama_kota' => "KABUPATEN ACEH UTARA"],
			['kode_kota' => 1112, 'id_provinsi' => 1, 'nama_kota' => "KABUPATEN ACEH BARAT DAYA"],
			['kode_kota' => 1113, 'id_provinsi' => 1, 'nama_kota' => "KABUPATEN GAYO LUES"],
			['kode_kota' => 1114, 'id_provinsi' => 1, 'nama_kota' => "KABUPATEN ACEH TAMIANG"],
			['kode_kota' => 1115, 'id_provinsi' => 1, 'nama_kota' => "KABUPATEN NAGAN RAYA"],
			['kode_kota' => 1116, 'id_provinsi' => 1, 'nama_kota' => "KABUPATEN ACEH JAYA"],
			['kode_kota' => 1117, 'id_provinsi' => 1, 'nama_kota' => "KABUPATEN BENER MERIAH"],
			['kode_kota' => 1118, 'id_provinsi' => 1, 'nama_kota' => "KABUPATEN PIDIE JAYA"],
			['kode_kota' => 1171, 'id_provinsi' => 1, 'nama_kota' => "KOTA BANDA ACEH"],
			['kode_kota' => 1172, 'id_provinsi' => 1, 'nama_kota' => "KOTA SABANG"],
			['kode_kota' => 1173, 'id_provinsi' => 1, 'nama_kota' => "KOTA LANGSA"],
			['kode_kota' => 1174, 'id_provinsi' => 1, 'nama_kota' => "KOTA LHOKSEUMAWE"],
			['kode_kota' => 1175, 'id_provinsi' => 1, 'nama_kota' => "KOTA SUBULUSSALAM"],
			['kode_kota' => 1201, 'id_provinsi' => 2, 'nama_kota' => "KABUPATEN NIAS"],
			['kode_kota' => 1202, 'id_provinsi' => 2, 'nama_kota' => "KABUPATEN MANDAILING NATAL"],
			['kode_kota' => 1203, 'id_provinsi' => 2, 'nama_kota' => "KABUPATEN TAPANULI SELATAN"],
			['kode_kota' => 1204, 'id_provinsi' => 2, 'nama_kota' => "KABUPATEN TAPANULI TENGAH"],
			['kode_kota' => 1205, 'id_provinsi' => 2, 'nama_kota' => "KABUPATEN TAPANULI UTARA"],
			['kode_kota' => 1206, 'id_provinsi' => 2, 'nama_kota' => "KABUPATEN TOBA SAMOSIR"],
			['kode_kota' => 1207, 'id_provinsi' => 2, 'nama_kota' => "KABUPATEN LABUHAN BATU"],
			['kode_kota' => 1208, 'id_provinsi' => 2, 'nama_kota' => "KABUPATEN ASAHAN"],
			['kode_kota' => 1209, 'id_provinsi' => 2, 'nama_kota' => "KABUPATEN SIMALUNGUN"],
			['kode_kota' => 1210, 'id_provinsi' => 2, 'nama_kota' => "KABUPATEN DAIRI"],
			['kode_kota' => 1211, 'id_provinsi' => 2, 'nama_kota' => "KABUPATEN KARO"],
			['kode_kota' => 1212, 'id_provinsi' => 2, 'nama_kota' => "KABUPATEN DELI SERDANG"],
			['kode_kota' => 1213, 'id_provinsi' => 2, 'nama_kota' => "KABUPATEN LANGKAT"],
			['kode_kota' => 1214, 'id_provinsi' => 2, 'nama_kota' => "KABUPATEN NIAS SELATAN"],
			['kode_kota' => 1215, 'id_provinsi' => 2, 'nama_kota' => "KABUPATEN HUMBANG HASUNDUTAN"],
			['kode_kota' => 1216, 'id_provinsi' => 2, 'nama_kota' => "KABUPATEN PAKPAK BHARAT"],
			['kode_kota' => 1217, 'id_provinsi' => 2, 'nama_kota' => "KABUPATEN SAMOSIR"],
			['kode_kota' => 1218, 'id_provinsi' => 2, 'nama_kota' => "KABUPATEN SERDANG BEDAGAI"],
			['kode_kota' => 1219, 'id_provinsi' => 2, 'nama_kota' => "KABUPATEN BATU BARA"],
			['kode_kota' => 1220, 'id_provinsi' => 2, 'nama_kota' => "KABUPATEN PADANG LAWAS UTARA"],
			['kode_kota' => 1221, 'id_provinsi' => 2, 'nama_kota' => "KABUPATEN PADANG LAWAS"],
			['kode_kota' => 1222, 'id_provinsi' => 2, 'nama_kota' => "KABUPATEN LABUHAN BATU SELATAN"],
			['kode_kota' => 1223, 'id_provinsi' => 2, 'nama_kota' => "KABUPATEN LABUHAN BATU UTARA"],
			['kode_kota' => 1224, 'id_provinsi' => 2, 'nama_kota' => "KABUPATEN NIAS UTARA"],
			['kode_kota' => 1225, 'id_provinsi' => 2, 'nama_kota' => "KABUPATEN NIAS BARAT"],
			['kode_kota' => 1271, 'id_provinsi' => 2, 'nama_kota' => "KOTA SIBOLGA"],
			['kode_kota' => 1272, 'id_provinsi' => 2, 'nama_kota' => "KOTA TANJUNG BALAI"],
			['kode_kota' => 1273, 'id_provinsi' => 2, 'nama_kota' => "KOTA PEMATANG SIANTAR"],
			['kode_kota' => 1274, 'id_provinsi' => 2, 'nama_kota' => "KOTA TEBING TINGGI"],
			['kode_kota' => 1275, 'id_provinsi' => 2, 'nama_kota' => "KOTA MEDAN"],
			['kode_kota' => 1276, 'id_provinsi' => 2, 'nama_kota' => "KOTA BINJAI"],
			['kode_kota' => 1277, 'id_provinsi' => 2, 'nama_kota' => "KOTA PADANGSIDIMPUAN"],
			['kode_kota' => 1278, 'id_provinsi' => 2, 'nama_kota' => "KOTA GUNUNGSITOLI"],
			['kode_kota' => 1301, 'id_provinsi' => 3, 'nama_kota' => "KABUPATEN KEPULAUAN MENTAWAI"],
			['kode_kota' => 1302, 'id_provinsi' => 3, 'nama_kota' => "KABUPATEN PESISIR SELATAN"],
			['kode_kota' => 1303, 'id_provinsi' => 3, 'nama_kota' => "KABUPATEN SOLOK"],
			['kode_kota' => 1304, 'id_provinsi' => 3, 'nama_kota' => "KABUPATEN SIJUNJUNG"],
			['kode_kota' => 1305, 'id_provinsi' => 3, 'nama_kota' => "KABUPATEN TANAH DATAR"],
			['kode_kota' => 1306, 'id_provinsi' => 3, 'nama_kota' => "KABUPATEN PADANG PARIAMAN"],
			['kode_kota' => 1307, 'id_provinsi' => 3, 'nama_kota' => "KABUPATEN AGAM"],
			['kode_kota' => 1308, 'id_provinsi' => 3, 'nama_kota' => "KABUPATEN LIMA PULUH KOTA"],
			['kode_kota' => 1309, 'id_provinsi' => 3, 'nama_kota' => "KABUPATEN PASAMAN"],
			['kode_kota' => 1310, 'id_provinsi' => 3, 'nama_kota' => "KABUPATEN SOLOK SELATAN"],
			['kode_kota' => 1311, 'id_provinsi' => 3, 'nama_kota' => "KABUPATEN DHARMASRAYA"],
			['kode_kota' => 1312, 'id_provinsi' => 3, 'nama_kota' => "KABUPATEN PASAMAN BARAT"],
			['kode_kota' => 1371, 'id_provinsi' => 3, 'nama_kota' => "KOTA PADANG"],
			['kode_kota' => 1372, 'id_provinsi' => 3, 'nama_kota' => "KOTA SOLOK"],
			['kode_kota' => 1373, 'id_provinsi' => 3, 'nama_kota' => "KOTA SAWAH LUNTO"],
			['kode_kota' => 1374, 'id_provinsi' => 3, 'nama_kota' => "KOTA PADANG PANJANG"],
			['kode_kota' => 1375, 'id_provinsi' => 3, 'nama_kota' => "KOTA BUKITTINGGI"],
			['kode_kota' => 1376, 'id_provinsi' => 3, 'nama_kota' => "KOTA PAYAKUMBUH"],
			['kode_kota' => 1377, 'id_provinsi' => 3, 'nama_kota' => "KOTA PARIAMAN"],
			['kode_kota' => 1401, 'id_provinsi' => 4, 'nama_kota' => "KABUPATEN KUANTAN SINGINGI"],
			['kode_kota' => 1402, 'id_provinsi' => 4, 'nama_kota' => "KABUPATEN INDRAGIRI HULU"],
			['kode_kota' => 1403, 'id_provinsi' => 4, 'nama_kota' => "KABUPATEN INDRAGIRI HILIR"],
			['kode_kota' => 1404, 'id_provinsi' => 4, 'nama_kota' => "KABUPATEN PELALAWAN"],
			['kode_kota' => 1405, 'id_provinsi' => 4, 'nama_kota' => "KABUPATEN SIAK"],
			['kode_kota' => 1406, 'id_provinsi' => 4, 'nama_kota' => "KABUPATEN KAMPAR"],
			['kode_kota' => 1407, 'id_provinsi' => 4, 'nama_kota' => "KABUPATEN ROKAN HULU"],
			['kode_kota' => 1408, 'id_provinsi' => 4, 'nama_kota' => "KABUPATEN BENGKALIS"],
			['kode_kota' => 1409, 'id_provinsi' => 4, 'nama_kota' => "KABUPATEN ROKAN HILIR"],
			['kode_kota' => 1410, 'id_provinsi' => 4, 'nama_kota' => "KABUPATEN KEPULAUAN MERANTI"],
			['kode_kota' => 1471, 'id_provinsi' => 4, 'nama_kota' => "KOTA PEKANBARU"],
			['kode_kota' => 1473, 'id_provinsi' => 4, 'nama_kota' => "KOTA DUMAI"],
			['kode_kota' => 1501, 'id_provinsi' => 5, 'nama_kota' => "KABUPATEN KERINCI"],
			['kode_kota' => 1502, 'id_provinsi' => 5, 'nama_kota' => "KABUPATEN MERANGIN"],
			['kode_kota' => 1503, 'id_provinsi' => 5, 'nama_kota' => "KABUPATEN SAROLANGUN"],
			['kode_kota' => 1504, 'id_provinsi' => 5, 'nama_kota' => "KABUPATEN BATANG HARI"],
			['kode_kota' => 1505, 'id_provinsi' => 5, 'nama_kota' => "KABUPATEN MUARO JAMBI"],
			['kode_kota' => 1506, 'id_provinsi' => 5, 'nama_kota' => "KABUPATEN TANJUNG JABUNG TIMUR"],
			['kode_kota' => 1507, 'id_provinsi' => 5, 'nama_kota' => "KABUPATEN TANJUNG JABUNG BARAT"],
			['kode_kota' => 1508, 'id_provinsi' => 5, 'nama_kota' => "KABUPATEN TEBO"],
			['kode_kota' => 1509, 'id_provinsi' => 5, 'nama_kota' => "KABUPATEN BUNGO"],
			['kode_kota' => 1571, 'id_provinsi' => 5, 'nama_kota' => "KOTA JAMBI"],
			['kode_kota' => 1572, 'id_provinsi' => 5, 'nama_kota' => "KOTA SUNGAI PENUH"],
			['kode_kota' => 1601, 'id_provinsi' => 6, 'nama_kota' => "KABUPATEN OGAN KOMERING ULU"],
			['kode_kota' => 1602, 'id_provinsi' => 6, 'nama_kota' => "KABUPATEN OGAN KOMERING ILIR"],
			['kode_kota' => 1603, 'id_provinsi' => 6, 'nama_kota' => "KABUPATEN MUARA ENIM"],
			['kode_kota' => 1604, 'id_provinsi' => 6, 'nama_kota' => "KABUPATEN LAHAT"],
			['kode_kota' => 1605, 'id_provinsi' => 6, 'nama_kota' => "KABUPATEN MUSI RAWAS"],
			['kode_kota' => 1606, 'id_provinsi' => 6, 'nama_kota' => "KABUPATEN MUSI BANYUASIN"],
			['kode_kota' => 1607, 'id_provinsi' => 6, 'nama_kota' => "KABUPATEN BANYU ASIN"],
			['kode_kota' => 1608, 'id_provinsi' => 6, 'nama_kota' => "KABUPATEN OGAN KOMERING ULU SELATAN"],
			['kode_kota' => 1609, 'id_provinsi' => 6, 'nama_kota' => "KABUPATEN OGAN KOMERING ULU TIMUR"],
			['kode_kota' => 1610, 'id_provinsi' => 6, 'nama_kota' => "KABUPATEN OGAN ILIR"],
			['kode_kota' => 1611, 'id_provinsi' => 6, 'nama_kota' => "KABUPATEN EMPAT LAWANG"],
			['kode_kota' => 1612, 'id_provinsi' => 6, 'nama_kota' => "KABUPATEN PENUKAL ABAB LEMATANG ILIR"],
			['kode_kota' => 1613, 'id_provinsi' => 6, 'nama_kota' => "KABUPATEN MUSI RAWAS UTARA"],
			['kode_kota' => 1671, 'id_provinsi' => 6, 'nama_kota' => "KOTA PALEMBANG"],
			['kode_kota' => 1672, 'id_provinsi' => 6, 'nama_kota' => "KOTA PRABUMULIH"],
			['kode_kota' => 1673, 'id_provinsi' => 6, 'nama_kota' => "KOTA PAGAR ALAM"],
			['kode_kota' => 1674, 'id_provinsi' => 6, 'nama_kota' => "KOTA LUBUKLINGGAU"],
			['kode_kota' => 1701, 'id_provinsi' => 7, 'nama_kota' => "KABUPATEN BENGKULU SELATAN"],
			['kode_kota' => 1702, 'id_provinsi' => 7, 'nama_kota' => "KABUPATEN REJANG LEBONG"],
			['kode_kota' => 1703, 'id_provinsi' => 7, 'nama_kota' => "KABUPATEN BENGKULU UTARA"],
			['kode_kota' => 1704, 'id_provinsi' => 7, 'nama_kota' => "KABUPATEN KAUR"],
			['kode_kota' => 1705, 'id_provinsi' => 7, 'nama_kota' => "KABUPATEN SELUMA"],
			['kode_kota' => 1706, 'id_provinsi' => 7, 'nama_kota' => "KABUPATEN MUKOMUKO"],
			['kode_kota' => 1707, 'id_provinsi' => 7, 'nama_kota' => "KABUPATEN LEBONG"],
			['kode_kota' => 1708, 'id_provinsi' => 7, 'nama_kota' => "KABUPATEN KEPAHIANG"],
			['kode_kota' => 1709, 'id_provinsi' => 7, 'nama_kota' => "KABUPATEN BENGKULU TENGAH"],
			['kode_kota' => 1771, 'id_provinsi' => 7, 'nama_kota' => "KOTA BENGKULU"],
			['kode_kota' => 1801, 'id_provinsi' => 8, 'nama_kota' => "KABUPATEN LAMPUNG BARAT"],
			['kode_kota' => 1802, 'id_provinsi' => 8, 'nama_kota' => "KABUPATEN TANGGAMUS"],
			['kode_kota' => 1803, 'id_provinsi' => 8, 'nama_kota' => "KABUPATEN LAMPUNG SELATAN"],
			['kode_kota' => 1804, 'id_provinsi' => 8, 'nama_kota' => "KABUPATEN LAMPUNG TIMUR"],
			['kode_kota' => 1805, 'id_provinsi' => 8, 'nama_kota' => "KABUPATEN LAMPUNG TENGAH"],
			['kode_kota' => 1806, 'id_provinsi' => 8, 'nama_kota' => "KABUPATEN LAMPUNG UTARA"],
			['kode_kota' => 1807, 'id_provinsi' => 8, 'nama_kota' => "KABUPATEN WAY KANAN"],
			['kode_kota' => 1808, 'id_provinsi' => 8, 'nama_kota' => "KABUPATEN TULANGBAWANG"],
			['kode_kota' => 1809, 'id_provinsi' => 8, 'nama_kota' => "KABUPATEN PESAWARAN"],
			['kode_kota' => 1810, 'id_provinsi' => 8, 'nama_kota' => "KABUPATEN PRINGSEWU"],
			['kode_kota' => 1811, 'id_provinsi' => 8, 'nama_kota' => "KABUPATEN MESUJI"],
			['kode_kota' => 1812, 'id_provinsi' => 8, 'nama_kota' => "KABUPATEN TULANG BAWANG BARAT"],
			['kode_kota' => 1813, 'id_provinsi' => 8, 'nama_kota' => "KABUPATEN PESISIR BARAT"],
			['kode_kota' => 1871, 'id_provinsi' => 8, 'nama_kota' => "KOTA BANDAR LAMPUNG"],
			['kode_kota' => 1872, 'id_provinsi' => 8, 'nama_kota' => "KOTA METRO"],
			['kode_kota' => 1901, 'id_provinsi' => 9, 'nama_kota' => "KABUPATEN BANGKA"],
			['kode_kota' => 1902, 'id_provinsi' => 9, 'nama_kota' => "KABUPATEN BELITUNG"],
			['kode_kota' => 1903, 'id_provinsi' => 9, 'nama_kota' => "KABUPATEN BANGKA BARAT"],
			['kode_kota' => 1904, 'id_provinsi' => 9, 'nama_kota' => "KABUPATEN BANGKA TENGAH"],
			['kode_kota' => 1905, 'id_provinsi' => 9, 'nama_kota' => "KABUPATEN BANGKA SELATAN"],
			['kode_kota' => 1906, 'id_provinsi' => 9, 'nama_kota' => "KABUPATEN BELITUNG TIMUR"],
			['kode_kota' => 1971, 'id_provinsi' => 9, 'nama_kota' => "KOTA PANGKAL PINANG"],
			['kode_kota' => 2101, 'id_provinsi' => 10, 'nama_kota' => "KABUPATEN KARIMUN"],
			['kode_kota' => 2102, 'id_provinsi' => 10, 'nama_kota' => "KABUPATEN BINTAN"],
			['kode_kota' => 2103, 'id_provinsi' => 10, 'nama_kota' => "KABUPATEN NATUNA"],
			['kode_kota' => 2104, 'id_provinsi' => 10, 'nama_kota' => "KABUPATEN LINGGA"],
			['kode_kota' => 2105, 'id_provinsi' => 10, 'nama_kota' => "KABUPATEN KEPULAUAN ANAMBAS"],
			['kode_kota' => 2171, 'id_provinsi' => 10, 'nama_kota' => "KOTA BATAM"],
			['kode_kota' => 2172, 'id_provinsi' => 10, 'nama_kota' => "KOTA TANJUNG PINANG"],
			['kode_kota' => 3101, 'id_provinsi' => 11, 'nama_kota' => "KABUPATEN KEPULAUAN SERIBU"],
			['kode_kota' => 3171, 'id_provinsi' => 11, 'nama_kota' => "KOTA JAKARTA SELATAN"],
			['kode_kota' => 3172, 'id_provinsi' => 11, 'nama_kota' => "KOTA JAKARTA TIMUR"],
			['kode_kota' => 3173, 'id_provinsi' => 11, 'nama_kota' => "KOTA JAKARTA PUSAT"],
			['kode_kota' => 3174, 'id_provinsi' => 11, 'nama_kota' => "KOTA JAKARTA BARAT"],
			['kode_kota' => 3175, 'id_provinsi' => 11, 'nama_kota' => "KOTA JAKARTA UTARA"],
			['kode_kota' => 3201, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN BOGOR"],
			['kode_kota' => 3202, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN SUKABUMI"],
			['kode_kota' => 3203, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN CIANJUR"],
			['kode_kota' => 3204, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN BANDUNG"],
			['kode_kota' => 3205, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN GARUT"],
			['kode_kota' => 3206, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN TASIKMALAYA"],
			['kode_kota' => 3207, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN CIAMIS"],
			['kode_kota' => 3208, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN KUNINGAN"],
			['kode_kota' => 3209, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN CIREBON"],
			['kode_kota' => 3210, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN MAJALENGKA"],
			['kode_kota' => 3211, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN SUMEDANG"],
			['kode_kota' => 3212, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN INDRAMAYU"],
			['kode_kota' => 3213, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN SUBANG"],
			['kode_kota' => 3214, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN PURWAKARTA"],
			['kode_kota' => 3215, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN KARAWANG"],
			['kode_kota' => 3216, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN BEKASI"],
			['kode_kota' => 3217, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN BANDUNG BARAT"],
			['kode_kota' => 3218, 'id_provinsi' => 12, 'nama_kota' => "KABUPATEN PANGANDARAN"],
			['kode_kota' => 3271, 'id_provinsi' => 12, 'nama_kota' => "KOTA BOGOR"],
			['kode_kota' => 3272, 'id_provinsi' => 12, 'nama_kota' => "KOTA SUKABUMI"],
			['kode_kota' => 3273, 'id_provinsi' => 12, 'nama_kota' => "KOTA BANDUNG"],
			['kode_kota' => 3274, 'id_provinsi' => 12, 'nama_kota' => "KOTA CIREBON"],
			['kode_kota' => 3275, 'id_provinsi' => 12, 'nama_kota' => "KOTA BEKASI"],
			['kode_kota' => 3276, 'id_provinsi' => 12, 'nama_kota' => "KOTA DEPOK"],
			['kode_kota' => 3277, 'id_provinsi' => 12, 'nama_kota' => "KOTA CIMAHI"],
			['kode_kota' => 3278, 'id_provinsi' => 12, 'nama_kota' => "KOTA TASIKMALAYA"],
			['kode_kota' => 3279, 'id_provinsi' => 12, 'nama_kota' => "KOTA BANJAR"],
			['kode_kota' => 3301, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN CILACAP"],
			['kode_kota' => 3302, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN BANYUMAS"],
			['kode_kota' => 3303, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN PURBALINGGA"],
			['kode_kota' => 3304, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN BANJARNEGARA"],
			['kode_kota' => 3305, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN KEBUMEN"],
			['kode_kota' => 3306, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN PURWOREJO"],
			['kode_kota' => 3307, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN WONOSOBO"],
			['kode_kota' => 3308, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN MAGELANG"],
			['kode_kota' => 3309, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN BOYOLALI"],
			['kode_kota' => 3310, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN KLATEN"],
			['kode_kota' => 3311, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN SUKOHARJO"],
			['kode_kota' => 3312, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN WONOGIRI"],
			['kode_kota' => 3313, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN KARANGANYAR"],
			['kode_kota' => 3314, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN SRAGEN"],
			['kode_kota' => 3315, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN GROBOGAN"],
			['kode_kota' => 3316, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN BLORA"],
			['kode_kota' => 3317, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN REMBANG"],
			['kode_kota' => 3318, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN PATI"],
			['kode_kota' => 3319, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN KUDUS"],
			['kode_kota' => 3320, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN JEPARA"],
			['kode_kota' => 3321, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN DEMAK"],
			['kode_kota' => 3322, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN SEMARANG"],
			['kode_kota' => 3323, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN TEMANGGUNG"],
			['kode_kota' => 3324, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN KENDAL"],
			['kode_kota' => 3325, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN BATANG"],
			['kode_kota' => 3326, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN PEKALONGAN"],
			['kode_kota' => 3327, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN PEMALANG"],
			['kode_kota' => 3328, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN TEGAL"],
			['kode_kota' => 3329, 'id_provinsi' => 13, 'nama_kota' => "KABUPATEN BREBES"],
			['kode_kota' => 3371, 'id_provinsi' => 13, 'nama_kota' => "KOTA MAGELANG"],
			['kode_kota' => 3372, 'id_provinsi' => 13, 'nama_kota' => "KOTA SURAKARTA"],
			['kode_kota' => 3373, 'id_provinsi' => 13, 'nama_kota' => "KOTA SALATIGA"],
			['kode_kota' => 3374, 'id_provinsi' => 13, 'nama_kota' => "KOTA SEMARANG"],
			['kode_kota' => 3375, 'id_provinsi' => 13, 'nama_kota' => "KOTA PEKALONGAN"],
			['kode_kota' => 3376, 'id_provinsi' => 13, 'nama_kota' => "KOTA TEGAL"],
			['kode_kota' => 3401, 'id_provinsi' => 14, 'nama_kota' => "KABUPATEN KULON PROGO"],
			['kode_kota' => 3402, 'id_provinsi' => 14, 'nama_kota' => "KABUPATEN BANTUL"],
			['kode_kota' => 3403, 'id_provinsi' => 14, 'nama_kota' => "KABUPATEN GUNUNG KIDUL"],
			['kode_kota' => 3404, 'id_provinsi' => 14, 'nama_kota' => "KABUPATEN SLEMAN"],
			['kode_kota' => 3471, 'id_provinsi' => 14, 'nama_kota' => "KOTA YOGYAKARTA"],
			['kode_kota' => 3501, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN PACITAN"],
			['kode_kota' => 3502, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN PONOROGO"],
			['kode_kota' => 3503, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN TRENGGALEK"],
			['kode_kota' => 3504, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN TULUNGAGUNG"],
			['kode_kota' => 3505, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN BLITAR"],
			['kode_kota' => 3506, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN KEDIRI"],
			['kode_kota' => 3507, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN MALANG"],
			['kode_kota' => 3508, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN LUMAJANG"],
			['kode_kota' => 3509, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN JEMBER"],
			['kode_kota' => 3510, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN BANYUWANGI"],
			['kode_kota' => 3511, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN BONDOWOSO"],
			['kode_kota' => 3512, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN SITUBONDO"],
			['kode_kota' => 3513, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN PROBOLINGGO"],
			['kode_kota' => 3514, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN PASURUAN"],
			['kode_kota' => 3515, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN SIDOARJO"],
			['kode_kota' => 3516, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN MOJOKERTO"],
			['kode_kota' => 3517, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN JOMBANG"],
			['kode_kota' => 3518, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN NGANJUK"],
			['kode_kota' => 3519, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN MADIUN"],
			['kode_kota' => 3520, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN MAGETAN"],
			['kode_kota' => 3521, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN NGAWI"],
			['kode_kota' => 3522, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN BOJONEGORO"],
			['kode_kota' => 3523, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN TUBAN"],
			['kode_kota' => 3524, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN LAMONGAN"],
			['kode_kota' => 3525, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN GRESIK"],
			['kode_kota' => 3526, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN BANGKALAN"],
			['kode_kota' => 3527, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN SAMPANG"],
			['kode_kota' => 3528, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN PAMEKASAN"],
			['kode_kota' => 3529, 'id_provinsi' => 15, 'nama_kota' => "KABUPATEN SUMENEP"],
			['kode_kota' => 3571, 'id_provinsi' => 15, 'nama_kota' => "KOTA KEDIRI"],
			['kode_kota' => 3572, 'id_provinsi' => 15, 'nama_kota' => "KOTA BLITAR"],
			['kode_kota' => 3573, 'id_provinsi' => 15, 'nama_kota' => "KOTA MALANG"],
			['kode_kota' => 3574, 'id_provinsi' => 15, 'nama_kota' => "KOTA PROBOLINGGO"],
			['kode_kota' => 3575, 'id_provinsi' => 15, 'nama_kota' => "KOTA PASURUAN"],
			['kode_kota' => 3576, 'id_provinsi' => 15, 'nama_kota' => "KOTA MOJOKERTO"],
			['kode_kota' => 3577, 'id_provinsi' => 15, 'nama_kota' => "KOTA MADIUN"],
			['kode_kota' => 3578, 'id_provinsi' => 15, 'nama_kota' => "KOTA SURABAYA"],
			['kode_kota' => 3579, 'id_provinsi' => 15, 'nama_kota' => "KOTA BATU"],
			['kode_kota' => 3601, 'id_provinsi' => 16, 'nama_kota' => "KABUPATEN PANDEGLANG"],
			['kode_kota' => 3602, 'id_provinsi' => 16, 'nama_kota' => "KABUPATEN LEBAK"],
			['kode_kota' => 3603, 'id_provinsi' => 16, 'nama_kota' => "KABUPATEN TANGERANG"],
			['kode_kota' => 3604, 'id_provinsi' => 16, 'nama_kota' => "KABUPATEN SERANG"],
			['kode_kota' => 3671, 'id_provinsi' => 16, 'nama_kota' => "KOTA TANGERANG"],
			['kode_kota' => 3672, 'id_provinsi' => 16, 'nama_kota' => "KOTA CILEGON"],
			['kode_kota' => 3673, 'id_provinsi' => 16, 'nama_kota' => "KOTA SERANG"],
			['kode_kota' => 3674, 'id_provinsi' => 16, 'nama_kota' => "KOTA TANGERANG SELATAN"],
			['kode_kota' => 5101, 'id_provinsi' => 17, 'nama_kota' => "KABUPATEN JEMBRANA"],
			['kode_kota' => 5102, 'id_provinsi' => 17, 'nama_kota' => "KABUPATEN TABANAN"],
			['kode_kota' => 5103, 'id_provinsi' => 17, 'nama_kota' => "KABUPATEN BADUNG"],
			['kode_kota' => 5104, 'id_provinsi' => 17, 'nama_kota' => "KABUPATEN GIANYAR"],
			['kode_kota' => 5105, 'id_provinsi' => 17, 'nama_kota' => "KABUPATEN KLUNGKUNG"],
			['kode_kota' => 5106, 'id_provinsi' => 17, 'nama_kota' => "KABUPATEN BANGLI"],
			['kode_kota' => 5107, 'id_provinsi' => 17, 'nama_kota' => "KABUPATEN KARANG ASEM"],
			['kode_kota' => 5108, 'id_provinsi' => 17, 'nama_kota' => "KABUPATEN BULELENG"],
			['kode_kota' => 5171, 'id_provinsi' => 17, 'nama_kota' => "KOTA DENPASAR"],
			['kode_kota' => 5201, 'id_provinsi' => 18, 'nama_kota' => "KABUPATEN LOMBOK BARAT"],
			['kode_kota' => 5202, 'id_provinsi' => 18, 'nama_kota' => "KABUPATEN LOMBOK TENGAH"],
			['kode_kota' => 5203, 'id_provinsi' => 18, 'nama_kota' => "KABUPATEN LOMBOK TIMUR"],
			['kode_kota' => 5204, 'id_provinsi' => 18, 'nama_kota' => "KABUPATEN SUMBAWA"],
			['kode_kota' => 5205, 'id_provinsi' => 18, 'nama_kota' => "KABUPATEN DOMPU"],
			['kode_kota' => 5206, 'id_provinsi' => 18, 'nama_kota' => "KABUPATEN BIMA"],
			['kode_kota' => 5207, 'id_provinsi' => 18, 'nama_kota' => "KABUPATEN SUMBAWA BARAT"],
			['kode_kota' => 5208, 'id_provinsi' => 18, 'nama_kota' => "KABUPATEN LOMBOK UTARA"],
			['kode_kota' => 5271, 'id_provinsi' => 18, 'nama_kota' => "KOTA MATARAM"],
			['kode_kota' => 5272, 'id_provinsi' => 18, 'nama_kota' => "KOTA BIMA"],
			['kode_kota' => 5301, 'id_provinsi' => 19, 'nama_kota' => "KABUPATEN SUMBA BARAT"],
			['kode_kota' => 5302, 'id_provinsi' => 19, 'nama_kota' => "KABUPATEN SUMBA TIMUR"],
			['kode_kota' => 5303, 'id_provinsi' => 19, 'nama_kota' => "KABUPATEN KUPANG"],
			['kode_kota' => 5304, 'id_provinsi' => 19, 'nama_kota' => "KABUPATEN TIMOR TENGAH SELATAN"],
			['kode_kota' => 5305, 'id_provinsi' => 19, 'nama_kota' => "KABUPATEN TIMOR TENGAH UTARA"],
			['kode_kota' => 5306, 'id_provinsi' => 19, 'nama_kota' => "KABUPATEN BELU"],
			['kode_kota' => 5307, 'id_provinsi' => 19, 'nama_kota' => "KABUPATEN ALOR"],
			['kode_kota' => 5308, 'id_provinsi' => 19, 'nama_kota' => "KABUPATEN LEMBATA"],
			['kode_kota' => 5309, 'id_provinsi' => 19, 'nama_kota' => "KABUPATEN FLORES TIMUR"],
			['kode_kota' => 5310, 'id_provinsi' => 19, 'nama_kota' => "KABUPATEN SIKKA"],
			['kode_kota' => 5311, 'id_provinsi' => 19, 'nama_kota' => "KABUPATEN ENDE"],
			['kode_kota' => 5312, 'id_provinsi' => 19, 'nama_kota' => "KABUPATEN NGADA"],
			['kode_kota' => 5313, 'id_provinsi' => 19, 'nama_kota' => "KABUPATEN MANGGARAI"],
			['kode_kota' => 5314, 'id_provinsi' => 19, 'nama_kota' => "KABUPATEN ROTE NDAO"],
			['kode_kota' => 5315, 'id_provinsi' => 19, 'nama_kota' => "KABUPATEN MANGGARAI BARAT"],
			['kode_kota' => 5316, 'id_provinsi' => 19, 'nama_kota' => "KABUPATEN SUMBA TENGAH"],
			['kode_kota' => 5317, 'id_provinsi' => 19, 'nama_kota' => "KABUPATEN SUMBA BARAT DAYA"],
			['kode_kota' => 5318, 'id_provinsi' => 19, 'nama_kota' => "KABUPATEN NAGEKEO"],
			['kode_kota' => 5319, 'id_provinsi' => 19, 'nama_kota' => "KABUPATEN MANGGARAI TIMUR"],
			['kode_kota' => 5320, 'id_provinsi' => 19, 'nama_kota' => "KABUPATEN SABU RAIJUA"],
			['kode_kota' => 5321, 'id_provinsi' => 19, 'nama_kota' => "KABUPATEN MALAKA"],
			['kode_kota' => 5371, 'id_provinsi' => 19, 'nama_kota' => "KOTA KUPANG"],
			['kode_kota' => 6101, 'id_provinsi' => 20, 'nama_kota' => "KABUPATEN SAMBAS"],
			['kode_kota' => 6102, 'id_provinsi' => 20, 'nama_kota' => "KABUPATEN BENGKAYANG"],
			['kode_kota' => 6103, 'id_provinsi' => 20, 'nama_kota' => "KABUPATEN LANDAK"],
			['kode_kota' => 6104, 'id_provinsi' => 20, 'nama_kota' => "KABUPATEN MEMPAWAH"],
			['kode_kota' => 6105, 'id_provinsi' => 20, 'nama_kota' => "KABUPATEN SANGGAU"],
			['kode_kota' => 6106, 'id_provinsi' => 20, 'nama_kota' => "KABUPATEN KETAPANG"],
			['kode_kota' => 6107, 'id_provinsi' => 20, 'nama_kota' => "KABUPATEN SINTANG"],
			['kode_kota' => 6108, 'id_provinsi' => 20, 'nama_kota' => "KABUPATEN KAPUAS HULU"],
			['kode_kota' => 6109, 'id_provinsi' => 20, 'nama_kota' => "KABUPATEN SEKADAU"],
			['kode_kota' => 6110, 'id_provinsi' => 20, 'nama_kota' => "KABUPATEN MELAWI"],
			['kode_kota' => 6111, 'id_provinsi' => 20, 'nama_kota' => "KABUPATEN KAYONG UTARA"],
			['kode_kota' => 6112, 'id_provinsi' => 20, 'nama_kota' => "KABUPATEN KUBU RAYA"],
			['kode_kota' => 6171, 'id_provinsi' => 20, 'nama_kota' => "KOTA PONTIANAK"],
			['kode_kota' => 6172, 'id_provinsi' => 20, 'nama_kota' => "KOTA SINGKAWANG"],
			['kode_kota' => 6201, 'id_provinsi' => 21, 'nama_kota' => "KABUPATEN KOTAWARINGIN BARAT"],
			['kode_kota' => 6202, 'id_provinsi' => 21, 'nama_kota' => "KABUPATEN KOTAWARINGIN TIMUR"],
			['kode_kota' => 6203, 'id_provinsi' => 21, 'nama_kota' => "KABUPATEN KAPUAS"],
			['kode_kota' => 6204, 'id_provinsi' => 21, 'nama_kota' => "KABUPATEN BARITO SELATAN"],
			['kode_kota' => 6205, 'id_provinsi' => 21, 'nama_kota' => "KABUPATEN BARITO UTARA"],
			['kode_kota' => 6206, 'id_provinsi' => 21, 'nama_kota' => "KABUPATEN SUKAMARA"],
			['kode_kota' => 6207, 'id_provinsi' => 21, 'nama_kota' => "KABUPATEN LAMANDAU"],
			['kode_kota' => 6208, 'id_provinsi' => 21, 'nama_kota' => "KABUPATEN SERUYAN"],
			['kode_kota' => 6209, 'id_provinsi' => 21, 'nama_kota' => "KABUPATEN KATINGAN"],
			['kode_kota' => 6210, 'id_provinsi' => 21, 'nama_kota' => "KABUPATEN PULANG PISAU"],
			['kode_kota' => 6211, 'id_provinsi' => 21, 'nama_kota' => "KABUPATEN GUNUNG MAS"],
			['kode_kota' => 6212, 'id_provinsi' => 21, 'nama_kota' => "KABUPATEN BARITO TIMUR"],
			['kode_kota' => 6213, 'id_provinsi' => 21, 'nama_kota' => "KABUPATEN MURUNG RAYA"],
			['kode_kota' => 6271, 'id_provinsi' => 21, 'nama_kota' => "KOTA PALANGKA RAYA"],
			['kode_kota' => 6301, 'id_provinsi' => 22, 'nama_kota' => "KABUPATEN TANAH LAUT"],
			['kode_kota' => 6302, 'id_provinsi' => 22, 'nama_kota' => "KABUPATEN KOTA BARU"],
			['kode_kota' => 6303, 'id_provinsi' => 22, 'nama_kota' => "KABUPATEN BANJAR"],
			['kode_kota' => 6304, 'id_provinsi' => 22, 'nama_kota' => "KABUPATEN BARITO KUALA"],
			['kode_kota' => 6305, 'id_provinsi' => 22, 'nama_kota' => "KABUPATEN TAPIN"],
			['kode_kota' => 6306, 'id_provinsi' => 22, 'nama_kota' => "KABUPATEN HULU SUNGAI SELATAN"],
			['kode_kota' => 6307, 'id_provinsi' => 22, 'nama_kota' => "KABUPATEN HULU SUNGAI TENGAH"],
			['kode_kota' => 6308, 'id_provinsi' => 22, 'nama_kota' => "KABUPATEN HULU SUNGAI UTARA"],
			['kode_kota' => 6309, 'id_provinsi' => 22, 'nama_kota' => "KABUPATEN TABALONG"],
			['kode_kota' => 6310, 'id_provinsi' => 22, 'nama_kota' => "KABUPATEN TANAH BUMBU"],
			['kode_kota' => 6311, 'id_provinsi' => 22, 'nama_kota' => "KABUPATEN BALANGAN"],
			['kode_kota' => 6371, 'id_provinsi' => 22, 'nama_kota' => "KOTA BANJARMASIN"],
			['kode_kota' => 6372, 'id_provinsi' => 22, 'nama_kota' => "KOTA BANJAR BARU"],
			['kode_kota' => 6401, 'id_provinsi' => 23, 'nama_kota' => "KABUPATEN PASER"],
			['kode_kota' => 6402, 'id_provinsi' => 23, 'nama_kota' => "KABUPATEN KUTAI BARAT"],
			['kode_kota' => 6403, 'id_provinsi' => 23, 'nama_kota' => "KABUPATEN KUTAI KARTANEGARA"],
			['kode_kota' => 6404, 'id_provinsi' => 23, 'nama_kota' => "KABUPATEN KUTAI TIMUR"],
			['kode_kota' => 6405, 'id_provinsi' => 23, 'nama_kota' => "KABUPATEN BERAU"],
			['kode_kota' => 6409, 'id_provinsi' => 23, 'nama_kota' => "KABUPATEN PENAJAM PASER UTARA"],
			['kode_kota' => 6411, 'id_provinsi' => 23, 'nama_kota' => "KABUPATEN MAHAKAM HULU"],
			['kode_kota' => 6471, 'id_provinsi' => 23, 'nama_kota' => "KOTA BALIKPAPAN"],
			['kode_kota' => 6472, 'id_provinsi' => 23, 'nama_kota' => "KOTA SAMARINDA"],
			['kode_kota' => 6474, 'id_provinsi' => 23, 'nama_kota' => "KOTA BONTANG"],
			['kode_kota' => 6501, 'id_provinsi' => 24, 'nama_kota' => "KABUPATEN MALINAU"],
			['kode_kota' => 6502, 'id_provinsi' => 24, 'nama_kota' => "KABUPATEN BULUNGAN"],
			['kode_kota' => 6503, 'id_provinsi' => 24, 'nama_kota' => "KABUPATEN TANA TIDUNG"],
			['kode_kota' => 6504, 'id_provinsi' => 24, 'nama_kota' => "KABUPATEN NUNUKAN"],
			['kode_kota' => 6571, 'id_provinsi' => 24, 'nama_kota' => "KOTA TARAKAN"],
			['kode_kota' => 7101, 'id_provinsi' => 25, 'nama_kota' => "KABUPATEN BOLAANG MONGONDOW"],
			['kode_kota' => 7102, 'id_provinsi' => 25, 'nama_kota' => "KABUPATEN MINAHASA"],
			['kode_kota' => 7103, 'id_provinsi' => 25, 'nama_kota' => "KABUPATEN KEPULAUAN SANGIHE"],
			['kode_kota' => 7104, 'id_provinsi' => 25, 'nama_kota' => "KABUPATEN KEPULAUAN TALAUD"],
			['kode_kota' => 7105, 'id_provinsi' => 25, 'nama_kota' => "KABUPATEN MINAHASA SELATAN"],
			['kode_kota' => 7106, 'id_provinsi' => 25, 'nama_kota' => "KABUPATEN MINAHASA UTARA"],
			['kode_kota' => 7107, 'id_provinsi' => 25, 'nama_kota' => "KABUPATEN BOLAANG MONGONDOW UTARA"],
			['kode_kota' => 7108, 'id_provinsi' => 25, 'nama_kota' => "KABUPATEN SIAU TAGULANDANG BIARO"],
			['kode_kota' => 7109, 'id_provinsi' => 25, 'nama_kota' => "KABUPATEN MINAHASA TENGGARA"],
			['kode_kota' => 7110, 'id_provinsi' => 25, 'nama_kota' => "KABUPATEN BOLAANG MONGONDOW SELATAN"],
			['kode_kota' => 7111, 'id_provinsi' => 25, 'nama_kota' => "KABUPATEN BOLAANG MONGONDOW TIMUR"],
			['kode_kota' => 7171, 'id_provinsi' => 25, 'nama_kota' => "KOTA MANADO"],
			['kode_kota' => 7172, 'id_provinsi' => 25, 'nama_kota' => "KOTA BITUNG"],
			['kode_kota' => 7173, 'id_provinsi' => 25, 'nama_kota' => "KOTA TOMOHON"],
			['kode_kota' => 7174, 'id_provinsi' => 25, 'nama_kota' => "KOTA KOTAMOBAGU"],
			['kode_kota' => 7201, 'id_provinsi' => 26, 'nama_kota' => "KABUPATEN BANGGAI KEPULAUAN"],
			['kode_kota' => 7202, 'id_provinsi' => 26, 'nama_kota' => "KABUPATEN BANGGAI"],
			['kode_kota' => 7203, 'id_provinsi' => 26, 'nama_kota' => "KABUPATEN MOROWALI"],
			['kode_kota' => 7204, 'id_provinsi' => 26, 'nama_kota' => "KABUPATEN POSO"],
			['kode_kota' => 7205, 'id_provinsi' => 26, 'nama_kota' => "KABUPATEN DONGGALA"],
			['kode_kota' => 7206, 'id_provinsi' => 26, 'nama_kota' => "KABUPATEN TOLI-TOLI"],
			['kode_kota' => 7207, 'id_provinsi' => 26, 'nama_kota' => "KABUPATEN BUOL"],
			['kode_kota' => 7208, 'id_provinsi' => 26, 'nama_kota' => "KABUPATEN PARIGI MOUTONG"],
			['kode_kota' => 7209, 'id_provinsi' => 26, 'nama_kota' => "KABUPATEN TOJO UNA-UNA"],
			['kode_kota' => 7210, 'id_provinsi' => 26, 'nama_kota' => "KABUPATEN SIGI"],
			['kode_kota' => 7211, 'id_provinsi' => 26, 'nama_kota' => "KABUPATEN BANGGAI LAUT"],
			['kode_kota' => 7212, 'id_provinsi' => 26, 'nama_kota' => "KABUPATEN MOROWALI UTARA"],
			['kode_kota' => 7271, 'id_provinsi' => 26, 'nama_kota' => "KOTA PALU"],
			['kode_kota' => 7301, 'id_provinsi' => 27, 'nama_kota' => "KABUPATEN KEPULAUAN SELAYAR"],
			['kode_kota' => 7302, 'id_provinsi' => 27, 'nama_kota' => "KABUPATEN BULUKUMBA"],
			['kode_kota' => 7303, 'id_provinsi' => 27, 'nama_kota' => "KABUPATEN BANTAENG"],
			['kode_kota' => 7304, 'id_provinsi' => 27, 'nama_kota' => "KABUPATEN JENEPONTO"],
			['kode_kota' => 7305, 'id_provinsi' => 27, 'nama_kota' => "KABUPATEN TAKALAR"],
			['kode_kota' => 7306, 'id_provinsi' => 27, 'nama_kota' => "KABUPATEN GOWA"],
			['kode_kota' => 7307, 'id_provinsi' => 27, 'nama_kota' => "KABUPATEN SINJAI"],
			['kode_kota' => 7308, 'id_provinsi' => 27, 'nama_kota' => "KABUPATEN MAROS"],
			['kode_kota' => 7309, 'id_provinsi' => 27, 'nama_kota' => "KABUPATEN PANGKAJENE DAN KEPULAUAN"],
			['kode_kota' => 7310, 'id_provinsi' => 27, 'nama_kota' => "KABUPATEN BARRU"],
			['kode_kota' => 7311, 'id_provinsi' => 27, 'nama_kota' => "KABUPATEN BONE"],
			['kode_kota' => 7312, 'id_provinsi' => 27, 'nama_kota' => "KABUPATEN SOPPENG"],
			['kode_kota' => 7313, 'id_provinsi' => 27, 'nama_kota' => "KABUPATEN WAJO"],
			['kode_kota' => 7314, 'id_provinsi' => 27, 'nama_kota' => "KABUPATEN SIDENRENG RAPPANG"],
			['kode_kota' => 7315, 'id_provinsi' => 27, 'nama_kota' => "KABUPATEN PINRANG"],
			['kode_kota' => 7316, 'id_provinsi' => 27, 'nama_kota' => "KABUPATEN ENREKANG"],
			['kode_kota' => 7317, 'id_provinsi' => 27, 'nama_kota' => "KABUPATEN LUWU"],
			['kode_kota' => 7318, 'id_provinsi' => 27, 'nama_kota' => "KABUPATEN TANA TORAJA"],
			['kode_kota' => 7322, 'id_provinsi' => 27, 'nama_kota' => "KABUPATEN LUWU UTARA"],
			['kode_kota' => 7325, 'id_provinsi' => 27, 'nama_kota' => "KABUPATEN LUWU TIMUR"],
			['kode_kota' => 7326, 'id_provinsi' => 27, 'nama_kota' => "KABUPATEN TORAJA UTARA"],
			['kode_kota' => 7371, 'id_provinsi' => 27, 'nama_kota' => "KOTA MAKASSAR"],
			['kode_kota' => 7372, 'id_provinsi' => 27, 'nama_kota' => "KOTA PAREPARE"],
			['kode_kota' => 7373, 'id_provinsi' => 27, 'nama_kota' => "KOTA PALOPO"],
			['kode_kota' => 7401, 'id_provinsi' => 28, 'nama_kota' => "KABUPATEN BUTON"],
			['kode_kota' => 7402, 'id_provinsi' => 28, 'nama_kota' => "KABUPATEN MUNA"],
			['kode_kota' => 7403, 'id_provinsi' => 28, 'nama_kota' => "KABUPATEN KONAWE"],
			['kode_kota' => 7404, 'id_provinsi' => 28, 'nama_kota' => "KABUPATEN KOLAKA"],
			['kode_kota' => 7405, 'id_provinsi' => 28, 'nama_kota' => "KABUPATEN KONAWE SELATAN"],
			['kode_kota' => 7406, 'id_provinsi' => 28, 'nama_kota' => "KABUPATEN BOMBANA"],
			['kode_kota' => 7407, 'id_provinsi' => 28, 'nama_kota' => "KABUPATEN WAKATOBI"],
			['kode_kota' => 7408, 'id_provinsi' => 28, 'nama_kota' => "KABUPATEN KOLAKA UTARA"],
			['kode_kota' => 7409, 'id_provinsi' => 28, 'nama_kota' => "KABUPATEN BUTON UTARA"],
			['kode_kota' => 7410, 'id_provinsi' => 28, 'nama_kota' => "KABUPATEN KONAWE UTARA"],
			['kode_kota' => 7411, 'id_provinsi' => 28, 'nama_kota' => "KABUPATEN KOLAKA TIMUR"],
			['kode_kota' => 7412, 'id_provinsi' => 28, 'nama_kota' => "KABUPATEN KONAWE KEPULAUAN"],
			['kode_kota' => 7413, 'id_provinsi' => 28, 'nama_kota' => "KABUPATEN MUNA BARAT"],
			['kode_kota' => 7414, 'id_provinsi' => 28, 'nama_kota' => "KABUPATEN BUTON TENGAH"],
			['kode_kota' => 7415, 'id_provinsi' => 28, 'nama_kota' => "KABUPATEN BUTON SELATAN"],
			['kode_kota' => 7471, 'id_provinsi' => 28, 'nama_kota' => "KOTA KENDARI"],
			['kode_kota' => 7472, 'id_provinsi' => 28, 'nama_kota' => "KOTA BAUBAU"],
			['kode_kota' => 7501, 'id_provinsi' => 29, 'nama_kota' => "KABUPATEN BOALEMO"],
			['kode_kota' => 7502, 'id_provinsi' => 29, 'nama_kota' => "KABUPATEN GORONTALO"],
			['kode_kota' => 7503, 'id_provinsi' => 29, 'nama_kota' => "KABUPATEN POHUWATO"],
			['kode_kota' => 7504, 'id_provinsi' => 29, 'nama_kota' => "KABUPATEN BONE BOLANGO"],
			['kode_kota' => 7505, 'id_provinsi' => 29, 'nama_kota' => "KABUPATEN GORONTALO UTARA"],
			['kode_kota' => 7571, 'id_provinsi' => 29, 'nama_kota' => "KOTA GORONTALO"],
			['kode_kota' => 7601, 'id_provinsi' => 30, 'nama_kota' => "KABUPATEN MAJENE"],
			['kode_kota' => 7602, 'id_provinsi' => 30, 'nama_kota' => "KABUPATEN POLEWALI MANDAR"],
			['kode_kota' => 7603, 'id_provinsi' => 30, 'nama_kota' => "KABUPATEN MAMASA"],
			['kode_kota' => 7604, 'id_provinsi' => 30, 'nama_kota' => "KABUPATEN MAMUJU"],
			['kode_kota' => 7605, 'id_provinsi' => 30, 'nama_kota' => "KABUPATEN MAMUJU UTARA"],
			['kode_kota' => 7606, 'id_provinsi' => 30, 'nama_kota' => "KABUPATEN MAMUJU TENGAH"],
			['kode_kota' => 8101, 'id_provinsi' => 31, 'nama_kota' => "KABUPATEN MALUKU TENGGARA BARAT"],
			['kode_kota' => 8102, 'id_provinsi' => 31, 'nama_kota' => "KABUPATEN MALUKU TENGGARA"],
			['kode_kota' => 8103, 'id_provinsi' => 31, 'nama_kota' => "KABUPATEN MALUKU TENGAH"],
			['kode_kota' => 8104, 'id_provinsi' => 31, 'nama_kota' => "KABUPATEN BURU"],
			['kode_kota' => 8105, 'id_provinsi' => 31, 'nama_kota' => "KABUPATEN KEPULAUAN ARU"],
			['kode_kota' => 8106, 'id_provinsi' => 31, 'nama_kota' => "KABUPATEN SERAM BAGIAN BARAT"],
			['kode_kota' => 8107, 'id_provinsi' => 31, 'nama_kota' => "KABUPATEN SERAM BAGIAN TIMUR"],
			['kode_kota' => 8108, 'id_provinsi' => 31, 'nama_kota' => "KABUPATEN MALUKU BARAT DAYA"],
			['kode_kota' => 8109, 'id_provinsi' => 31, 'nama_kota' => "KABUPATEN BURU SELATAN"],
			['kode_kota' => 8171, 'id_provinsi' => 31, 'nama_kota' => "KOTA AMBON"],
			['kode_kota' => 8172, 'id_provinsi' => 31, 'nama_kota' => "KOTA TUAL"],
			['kode_kota' => 8201, 'id_provinsi' => 32, 'nama_kota' => "KABUPATEN HALMAHERA BARAT"],
			['kode_kota' => 8202, 'id_provinsi' => 32, 'nama_kota' => "KABUPATEN HALMAHERA TENGAH"],
			['kode_kota' => 8203, 'id_provinsi' => 32, 'nama_kota' => "KABUPATEN KEPULAUAN SULA"],
			['kode_kota' => 8204, 'id_provinsi' => 32, 'nama_kota' => "KABUPATEN HALMAHERA SELATAN"],
			['kode_kota' => 8205, 'id_provinsi' => 32, 'nama_kota' => "KABUPATEN HALMAHERA UTARA"],
			['kode_kota' => 8206, 'id_provinsi' => 32, 'nama_kota' => "KABUPATEN HALMAHERA TIMUR"],
			['kode_kota' => 8207, 'id_provinsi' => 32, 'nama_kota' => "KABUPATEN PULAU MOROTAI"],
			['kode_kota' => 8208, 'id_provinsi' => 32, 'nama_kota' => "KABUPATEN PULAU TALIABU"],
			['kode_kota' => 8271, 'id_provinsi' => 32, 'nama_kota' => "KOTA TERNATE"],
			['kode_kota' => 8272, 'id_provinsi' => 32, 'nama_kota' => "KOTA TIDORE KEPULAUAN"],
			['kode_kota' => 9101, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN FAKFAK"],
			['kode_kota' => 9102, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN KAIMANA"],
			['kode_kota' => 9103, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN TELUK WONDAMA"],
			['kode_kota' => 9104, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN TELUK BINTUNI"],
			['kode_kota' => 9105, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN MANOKWARI"],
			['kode_kota' => 9106, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN SORONG SELATAN"],
			['kode_kota' => 9107, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN SORONG"],
			['kode_kota' => 9108, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN RAJA AMPAT"],
			['kode_kota' => 9109, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN TAMBRAUW"],
			['kode_kota' => 9110, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN MAYBRAT"],
			['kode_kota' => 9111, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN MANOKWARI SELATAN"],
			['kode_kota' => 9112, 'id_provinsi' => 33, 'nama_kota' => "KABUPATEN PEGUNUNGAN ARFAK"],
			['kode_kota' => 9171, 'id_provinsi' => 33, 'nama_kota' => "KOTA SORONG"],
			['kode_kota' => 9401, 'id_provinsi' => 34, 'nama_kota' => "KABUPATEN MERAUKE"],
			['kode_kota' => 9402, 'id_provinsi' => 34, 'nama_kota' => "KABUPATEN JAYAWIJAYA"],
			['kode_kota' => 9403, 'id_provinsi' => 34, 'nama_kota' => "KABUPATEN JAYAPURA"],
			['kode_kota' => 9404, 'id_provinsi' => 34, 'nama_kota' => "KABUPATEN NABIRE"],
			['kode_kota' => 9408, 'id_provinsi' => 34, 'nama_kota' => "KABUPATEN KEPULAUAN YAPEN"],
			['kode_kota' => 9409, 'id_provinsi' => 34, 'nama_kota' => "KABUPATEN BIAK NUMFOR"],
			['kode_kota' => 9410, 'id_provinsi' => 34, 'nama_kota' => "KABUPATEN PANIAI"],
			['kode_kota' => 9411, 'id_provinsi' => 34, 'nama_kota' => "KABUPATEN PUNCAK JAYA"],
			['kode_kota' => 9412, 'id_provinsi' => 34, 'nama_kota' => "KABUPATEN MIMIKA"],
			['kode_kota' => 9413, 'id_provinsi' => 34, 'nama_kota' => "KABUPATEN BOVEN DIGOEL"],
			['kode_kota' => 9414, 'id_provinsi' => 34, 'nama_kota' => "KABUPATEN MAPPI"],
			['kode_kota' => 9415, 'id_provinsi' => 34, 'nama_kota' => "KABUPATEN ASMAT"],
			['kode_kota' => 9416, 'id_provinsi' => 34, 'nama_kota' => "KABUPATEN YAHUKIMO"],
			['kode_kota' => 9417, 'id_provinsi' => 34, 'nama_kota' => "KABUPATEN PEGUNUNGAN BINTANG"],
			['kode_kota' => 9418, 'id_provinsi' => 34, 'nama_kota' => "KABUPATEN TOLIKARA"],
			['kode_kota' => 9419, 'id_provinsi' => 34, 'nama_kota' => "KABUPATEN SARMI"],
			['kode_kota' => 9420, 'id_provinsi' => 34, 'nama_kota' => "KABUPATEN KEEROM"],
			['kode_kota' => 9426, 'id_provinsi' => 34, 'nama_kota' => "KABUPATEN WAROPEN"],
			['kode_kota' => 9427, 'id_provinsi' => 34, 'nama_kota' => "KABUPATEN SUPIORI"],
			['kode_kota' => 9428, 'id_provinsi' => 34, 'nama_kota' => "KABUPATEN MAMBERAMO RAYA"],
			['kode_kota' => 9429, 'id_provinsi' => 34, 'nama_kota' => "KABUPATEN NDUGA"],
			['kode_kota' => 9430, 'id_provinsi' => 34, 'nama_kota' => "KABUPATEN LANNY JAYA"],
			['kode_kota' => 9431, 'id_provinsi' => 34, 'nama_kota' => "KABUPATEN MAMBERAMO TENGAH"],
			['kode_kota' => 9412, 'id_provinsi' => 34, 'nama_kota' => "KABUPATEN YALIMO"],
			['kode_kota' => 9413, 'id_provinsi' => 34, 'nama_kota' => "KABUPATEN PUNCAK"],
			['kode_kota' => 9434, 'id_provinsi' => 34, 'nama_kota' => "KABUPATEN DOGIYAI"],
			['kode_kota' => 9415, 'id_provinsi' => 34, 'nama_kota' => "KABUPATEN INTAN JAYA"],
			['kode_kota' => 9416, 'id_provinsi' => 34, 'nama_kota' => "KABUPATEN DEIYAI"],
			['kode_kota' => 9471, 'id_provinsi' => 34, 'nama_kota' => "KOTA JAYAPURA"]
			
        ];
        DB::table('kotas')->insert($kotas);
    }
}